### ISSUE TITLE
Home Page Product API Requests

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/StudentLoansBangazon.API#5]
## User Story
As a Developer, I should see two GET Requests in the ProductsController file: GetProductsByName and GetProductsByCategory. Both Methods should query the Products table and return items accordingly

## Development
* In the ProductsController File, create a GET Request called GetProductsByName that returns an IEnumerable<Product>. This request should call a method in the ProductRepository that queries the database by a Search term provided by the user
* In the ProductsController File, create a GET Request called GetProductsByCategory that returns an IEnumerable<Product>. This request should call a method in the ProductRepository that queries the database by a Category provided by the user

**Comment by matthewaustinbell** [comment]
@HeathJHMoore it looks like you got this ticket knocked out is that correct?
